version: '3.7'
networks:
    ev_network:
        external:
            name: evse_ev_network

services:
    dashboard:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            args:
                build: prod
        ports:
            - 3080:80
        networks:
            - ev_network
